version: "2.4"
services:
  db:
    image: mysql:latest
    healthcheck:
      test: "mysqladmin ping"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ling_508
